version: '3.8'
services:
  dev-portal-styling:
    image: docker.io/datawire/aes:1.14.2
    entrypoint: local-devportal
    command:
      - /content
    ports:
      - "1080:1080"
    volumes:
    - ".:/content"
